---
# https://docs.ansible.com/ansible/latest/collections/ansible/builtin/
- name: Installation du serveur
  hosts: remote
  become: yes

  pre_tasks:
    - name: "APT | Update & Upgrade"
      become: yes
      apt:
        upgrade: dist
        update_cache: yes

  tasks:

  roles:
    - {role: tools, tags: tools}
    - {role: docker, tags: docker}
    - {role: firewall, tags: firewall}
    # - {role: php, tags: php}
    - {role: nginx, tags: nginx}
    # - {role: pgsql, tags: pgsql}
    # - {role: app, tags: app}
    # - {role: mail, tags: mail}

