---
# https://docs.ansible.com/ansible/latest/collections/ansible/builtin/
- name: Installation du serveur
  hosts: remote
  become: yes

  pre_tasks:
    - name: "APT | Update & Upgrade"
      become: yes
      apt:
        upgrade: dist
        update_cache: yes

  tasks:

  roles:
    - {role: tools, tags: tools}
    - {role: docker, tags: docker, when: docker}
    - {role: firewall, tags: firewall}
    - {role: php, tags: php, when: not docker}
    - {role: nginx, tags: nginx}
    - {role: pgsql, tags: pgsql, when: not docker}
    - {role: node, tags: node, when: not docker}
    - {role: app, tags: app, when: not docker}
    # - {role: mail, tags: mail, when: not docker}
    - {role: stats, tags: stats, when: not docker}

