knpu_oauth2_client:
    clients:
        discord:
            type: discord
            client_id: '%env(DISCORD_ID)%'
            client_secret: '%env(DISCORD_SECRET)%'
            redirect_route: oauth_discord_check
            redirect_params: {}
        github:
            type: github
            client_id: '%env(GITHUB_ID)%'
            client_secret: '%env(GITHUB_SECRET)%'
            redirect_route: oauth_check
            redirect_params:
              service: github
        google:
            type: google
            client_id: '%env(GOOGLE_ID)%'
            client_secret: '%env(GOOGLE_SECRET)%'
            redirect_route: oauth_check
            redirect_params:
                service: google
