vich_uploader:
    db_driver: orm

    mappings:
      attachments:
        uri_prefix: /uploads/attachments
        upload_destination: '%kernel.project_dir%/public/uploads/attachments'
        namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        directory_namer:
          service: Vich\UploaderBundle\Naming\CurrentDateTimeDirectoryNamer
          options:
            date_time_format: 'Y' # will create directory "2018/23/09" for curent date "2018-09-23"
            date_time_property: createdAt # see above example
        inject_on_load: false
        delete_on_update: true
        delete_on_remove: true
      sources:
        upload_destination: '%kernel.project_dir%/downloads/sources'
        namer:
          service: Vich\UploaderBundle\Naming\PropertyNamer
          options: { property: 'slug'}
        directory_namer:
          service: App\Infrastructure\Storage\Naming\IdDirectoryNamer
        inject_on_load: false
        delete_on_update: true
        delete_on_remove: true
      icons:
        upload_destination: '%kernel.project_dir%/public/uploads/icons'
        uri_prefix: /uploads/icons
        namer:
          service: Vich\UploaderBundle\Naming\PropertyNamer
          options: { property: 'slug'}
