framework:
    cache:
        prefix_seed: grafikart/site
        app: cache.adapter.redis
        default_redis_provider: '%env(resolve:REDIS_URL)%'
        # Namespaced pools use the above "app" backend by default
        #pools:
            #my.dedicated.cache: null
