parameters:
  stripe_public_key: '%env(resolve:STRIPE_ID)%'
  stripe_secret_key: '%env(resolve:STRIPE_SECRET)%'
  stripe_webhook_secret: '%env(resolve:STRIPE_WEBHOOK_SECRET)%'

services:
  _defaults:
    autowire: true # Automatically injects dependencies in your services.
    autoconfigure: false # Automatically registers your services as commands, event subscribers, etc.
    public: false

  App\Infrastructure\Payment\Stripe\StripeApi:
    arguments: ['%stripe_secret_key%']

  App\Infrastructure\Payment\Stripe\StripeEventValueResolver:
    arguments: ['%stripe_webhook_secret%']
    tags:
      - { name: controller.argument_value_resolver, priority: 50 }
